apiVersion: v1
kind: Service
metadata:
  name: autoscale-runc
spec:
  selector:
    app: autoscale-runc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-runc-deployment
  labels:
    app: autoscale-runc
spec:
  selector:
    matchLabels:
      app: autoscale-runc
  replicas: 2
  template:
    metadata:
      labels:
        app: autoscale-runc
    spec:
      containers:
      - name: autoscale-runc
        image: didierdurand/autoscale-go
        ports:
        - containerPort: 8080