apiVersion: v1
kind: Service
metadata:
  name: autoscale-kata
spec:
  selector:
    app: autoscale-kata
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscale-kata-deployment
  labels:
    app: autoscale-kata
spec:
  selector:
    matchLabels:
      app: autoscale-kata
  replicas: 1
  template:
    metadata:
      labels:
        app: autoscale-kata
    spec:
      containers:
      - name: autoscale-kata
        image: didierdurand/autoscale-go
        ports:
        - containerPort: 8080