apiVersion: v1
kind: Service
metadata:
  name: helloworld-go
spec:
  selector:
    app: helloworld-go
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-go-deployment
  labels:
    app: helloworld-go
spec:
  selector:
    matchLabels:
      app: helloworld-go
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld-go
    spec:
      containers:
      - name: helloworld-go
        image: didierdurand/helloworld-go
        ports:
        - containerPort: 8080
        env:
        - name: TARGET
          value: "Knative"