apiVersion: v1
kind: Service
metadata:
  name: helloworld-runc
spec:
  selector:
    app: helloworld-runc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-runc-deployment
  labels:
    app: helloworld-runc
spec:
  selector:
    matchLabels:
      app: helloworld-runc
  replicas: 2
  template:
    metadata:
      labels:
        app: helloworld-runc
    spec:
      containers:
      - name: helloworld-runc
        image: didierdurand/helloworld-go
        ports:
        - containerPort: 8080
        env:
        - name: TARGET
          value: "Runc Containers"