apiVersion: v1
kind: Service
metadata:
  name: nginx-runc
spec:
  selector:
    app: nginx-runc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-runc-deployment
  labels:
    app: nginx-runc
spec:
  selector:
    matchLabels:
      app: nginx-runc
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-runc
    spec:
      containers:
      - name: nginx-runc
        image: nginx
        ports:
        - containerPort: 80